-- ==============================================================================
-- SUPABASE PLAYGROUND: Complete PostgreSQL Setup & Schema
-- ==============================================================================
-- Run this script in your Supabase Dashboard: SQL Editor -> New Query -> Run
-- ==============================================================================

-- 1. ENABLE EXTENSIONS
create extension if not exists vector;

-- ==============================================================================
-- 2. DATABASE DEMO: Students Table
-- ==============================================================================
create table if not exists public.students (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null default 'Student',
    score integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed initial students
insert into public.students (name, role, score)
values 
    ('Uma', 'Student', 85),
    ('Rahul', 'Student', 91),
    ('Sophia', 'Student', 94)
on conflict do nothing;

-- Enable Row Level Security (RLS) & allow anonymous access for this playground
alter table public.students enable row level security;

drop policy if exists "Allow public read students" on public.students;
create policy "Allow public read students" on public.students 
    for select using (true);

drop policy if exists "Allow public insert students" on public.students;
create policy "Allow public insert students" on public.students 
    for insert with check (true);

-- ==============================================================================
-- 3. STORAGE DEMO: learning-files Bucket
-- ==============================================================================
insert into storage.buckets (id, name, public)
values ('learning-files', 'learning-files', true)
on conflict (id) do update set public = true;

drop policy if exists "Allow public view learning-files" on storage.objects;
create policy "Allow public view learning-files" on storage.objects 
    for select using (bucket_id = 'learning-files');

drop policy if exists "Allow public upload learning-files" on storage.objects;
create policy "Allow public upload learning-files" on storage.objects 
    for insert with check (bucket_id = 'learning-files');

-- ==============================================================================
-- 4. REALTIME DEMO: Live Counter Table
-- ==============================================================================
create table if not exists public.live_counter (
    id int primary key default 1,
    count int not null default 24,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into public.live_counter (id, count)
values (1, 24)
on conflict (id) do nothing;

alter table public.live_counter enable row level security;

drop policy if exists "Allow public read live_counter" on public.live_counter;
create policy "Allow public read live_counter" on public.live_counter 
    for select using (true);

drop policy if exists "Allow public update live_counter" on public.live_counter;
create policy "Allow public update live_counter" on public.live_counter 
    for update using (true);

-- Add to Realtime Publication so Postgres pushes changes to WebSocket subscribers
do $$
begin
    if not exists (
        select 1 from pg_publication_tables 
        where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'live_counter'
    ) then
        alter publication supabase_realtime add table public.live_counter;
    end if;
end;
$$;

-- ==============================================================================
-- 5. PGVECTOR DEMO: Policy Documents Table & Search Function
-- ==============================================================================
create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    embedding vector(384) -- 384 dimensions matches standard mini-embeddings
);

alter table public.documents enable row level security;

drop policy if exists "Allow public read documents" on public.documents;
create policy "Allow public read documents" on public.documents 
    for select using (true);

drop policy if exists "Allow public insert documents" on public.documents;
create policy "Allow public insert documents" on public.documents 
    for insert with check (true);

-- pgvector Similarity Search RPC Function
create or replace function match_documents (
    query_embedding vector(384),
    match_threshold float,
    match_count int
)
returns table (
    id bigint,
    title text,
    content text,
    similarity float
)
language sql stable
as $$
    select
        documents.id,
        documents.title,
        documents.content,
        1 - (documents.embedding <=> query_embedding) as similarity
    from documents
    where 1 - (documents.embedding <=> query_embedding) > match_threshold
    order by similarity desc
    limit match_count;
$$;
